#include<iostream>
#include<fstream>
#include<filesystem>
#include<vector>
#include<string>

std::string filename;
std::filesystem::path tmp_dir = "/tmp/bread/";
std::filesystem::path cpp_dir = "/tmp/bread/temp.cpp";
std::string cppname;
std::vector<std::string> file_contents;

int compiler; // 1 = gcc, 2 = clang, if both, clang will be preferred due to faster compile time

int create_tmp_dir_if_not_exist() {
    try {
        if (!std::filesystem::is_directory(tmp_dir)) {
            std::filesystem::create_directory(tmp_dir);
            std::cout << "created tmp directory, first start?" << std::endl;
        }
    } catch (const std::filesystem::filesystem_error &e) {
        std::cout << "could not create tmp directory, " << e.what() << std::endl;
        return 1;
    }
    return 0;
}

int compile_cpp(std::string filepath) {

}

int compile_to_cpp(std::string filename) {
    std::ifstream breadfile;
    std::ofstream cpp_file;

    breadfile.open(filename);
    if (!breadfile.is_open()) {
        std::cerr << "error opening file" << std::endl;
        throw 500;
        return 1;
    }
    std::string c;
    while (std::getline(breadfile, c)) {
        file_contents.push_back(c);
    } // save file into vector
    breadfile.close();
    cpp_file.open(cpp_dir);
    if (!cpp_file.is_open()) {
        std::cerr << "error creating temporary cpp file" << std::endl;
        throw 500;
        return 1;
    }
    //for (std::string content : file_contents) {
    //    if (content.find("shrtct/")) {
    //        content.erase(0,7);
    //    }
    //} todo: shortcuts
    cpp_file << "//transpiled from the bread programming language, do not edit this file\n#include<iostream>\nint main() {\n";
    for (std::string content : file_contents) {
        if (content.find("print/") == 0) {
            content.erase(0, 6);
            cpp_file << "std::cout << \"" << content << "\";\n";
        } else if (content.find("int/") == 0 ) {
            content.erase(0, 4);
            size_t slash = content.find('/');
            if (slash != std::string::npos) {
                std::string int_name = content.substr(0, slash);
                std::string int_val = content.substr(slash + 1);
                cpp_file << "int " << int_name << " = " << int_val << ";\n";
            }
            
        } else if (content.find("bol/") == 0) {
            content.erase(0, 4);
            size_t slash = content.find('/');
            if (slash != std::string::npos) {
                std::string bol_name = content.substr(0, slash);
                std::string bol_val = content.substr(slash + 1);
                if (bol_val != "true" and bol_val != "false") {
                    std::cerr << "booleans can only be true or false!\nexpected: true / false\ngot: " << bol_val << "\nfor " << bol_name << std::endl;
                    throw 500;
                    return 1;
                }
                cpp_file << "bool " << bol_name << " = " << bol_val << ";\n";
            }
        } else if (content.find("str/") == 0) {
            content.erase(0, 4);
            size_t slash = content.find('/');
            if (slash != std::string::npos) {
                std::string str_name = content.substr(0, slash);
                std::string str_val = content.substr(slash + 1);
                cpp_file << "std::string " << str_val << " = \"" << str_val << "\";\n";
            }
        }
    }
    cpp_file << "return 0;\n}\n";
    cpp_file.close();
    return 0;
}

// checks for compilers on the machine
int find_compiler() {
    std::cout << "scanning for compilers..." << std::endl;
    std::string gcc = "gcc -v > /dev/null 2>&1";
    std::string clang = "clang++ -v > /dev/null 2>&1";
    int gcc_result = std::system(gcc.c_str());
    int clang_result = std::system(clang.c_str());
    if (gcc_result == 0) {
        std::cout << "gcc found" << std::endl;
        compiler = 1;
    } else if (clang_result == 0) {
        std::cout << "clang found" << std::endl;
        compiler = 2;
    } else if (clang_result == 0 && gcc_result == 0) {
        std::cout << "2 compilers found, clang will be preferred" << std::endl;
        compiler = 2;
    } else {
        std::cerr << "no compilers found, please install gcc or clang" << std::endl;
        throw 500;
        return 1;
    }
    return 0;
}

int main(int argc, char *argv[]) {
    if (argc < 2) {
        std::cout << "no arguments given, enter filename to compile .bread file" << std::endl;
        return 1;
    } else {
        filename = argv[1];
    }
    try {
        find_compiler();
    } catch (int e) {
        return 1;
    }
    create_tmp_dir_if_not_exist();
    try {
        compile_to_cpp(filename);
    } catch (int ercode) {
        return 1;
    }
    return 0;
}